name: omnilog_flutter
description: OmniLog for Flutter.
version: 0.0.1
repository: https://github.com/k1zerX/logger

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  omnilog: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dart_code_metrics: ^5.1.0
  lints: ^2.0.0
  test: ^1.22.0

flutter: