name: omnilog
description: OmniLog.
version: 0.0.1
repository: https://github.com/k1zerX/logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  equatable: ^2.0.0

dev_dependencies:
  dart_code_metrics: ^5.1.0
  lints: ^2.0.0
  test: ^1.22.0
